{
 "title": "App Health – Flask",
 "time": { "from": "2026-02-08T14:47:23.873Z", "to": "2026-02-08T15:02:23.873Z" },
 "panels": [
  {
   "title": "Application Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"application\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HTTP Requests by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (\n  rate(http_requests_total[1m])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, endpoint) (\n    rate(http_request_latency_seconds_bucket[5m])\n  )\n)\n",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total HTTP Requests (Traffic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (endpoint) (\n  rate(http_requests_total[1m])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}